export const rows = [
  {
    id: 1,
    nombreEvento: "Evento 1",
    tipoEvento: "Privado",
    fechaCreacion: "2024-03-01",
    fechaFin: "2024-03-05",
    status: "Activo",
    categoria: "Conferencia",
  },
  {
    id: 2,
    nombreEvento: "Evento 2",
    tipoEvento: "Público",
    fechaCreacion: "2024-03-02",
    fechaFin: "2024-03-06",
    status: "Cancelado",
    categoria: "Concierto",
  },
  {
    id: 3,
    nombreEvento: "Evento 3",
    tipoEvento: "Privado",
    fechaCreacion: "2024-03-03",
    fechaFin: "2024-03-07",
    status: "Pendiente",
    categoria: "Taller",
  },
  {
    id: 4,
    nombreEvento: "Evento 4",
    tipoEvento: "Público",
    fechaCreacion: "2024-03-04",
    fechaFin: "2024-03-08",
    status: "Finalizado",
    categoria: "Conferencia",
  },
  {
    id: 5,
    nombreEvento: "Evento 1",
    tipoEvento: "Privado",
    fechaCreacion: "2024-03-01",
    fechaFin: "2024-03-05",
    status: "Activo",
    categoria: "Conferencia",
  },
  {
    id: 6,
    nombreEvento: "Evento 2",
    tipoEvento: "Público",
    fechaCreacion: "2024-03-02",
    fechaFin: "2024-03-06",
    status: "Cancelado",
    categoria: "Concierto",
  },
  {
    id: 7,
    nombreEvento: "Evento 3",
    tipoEvento: "Privado",
    fechaCreacion: "2024-03-03",
    fechaFin: "2024-03-07",
    status: "Pendiente",
    categoria: "Taller",
  },
  {
    id: 8,
    nombreEvento: "Evento 4",
    tipoEvento: "Público",
    fechaCreacion: "2024-03-04",
    fechaFin: "2024-03-08",
    status: "Activo",
    categoria: "Conferencia",
  },
  {
    id: 9,
    nombreEvento: "Evento 1",
    tipoEvento: "Privado",
    fechaCreacion: "2024-03-01",
    fechaFin: "2024-03-05",
    status: "Activo",
    categoria: "Conferencia",
  },
  {
    id: 10,
    nombreEvento: "Evento 2",
    tipoEvento: "Público",
    fechaCreacion: "2024-03-02",
    fechaFin: "2024-03-06",
    status: "Cancelado",
    categoria: "Concierto",
  },
  {
    id: 11,
    nombreEvento: "Evento 3",
    tipoEvento: "Privado",
    fechaCreacion: "2024-03-03",
    fechaFin: "2024-03-07",
    status: "Pendiente",
    categoria: "Taller",
  },
  {
    id: 12,
    nombreEvento: "Evento 4",
    tipoEvento: "Público",
    fechaCreacion: "2024-03-04",
    fechaFin: "2024-03-08",
    status: "Activo",
    categoria: "Conferencia",
  },
  {
    id: 13,
    nombreEvento: "Evento 1",
    tipoEvento: "Privado",
    fechaCreacion: "2024-03-01",
    fechaFin: "2024-03-05",
    status: "Activo",
    categoria: "Conferencia",
  },
  {
    id: 14,
    nombreEvento: "Evento 2",
    tipoEvento: "Público",
    fechaCreacion: "2024-03-02",
    fechaFin: "2024-03-06",
    status: "Cancelado",
    categoria: "Concierto",
  },
  {
    id: 15,
    nombreEvento: "Evento 3",
    tipoEvento: "Privado",
    fechaCreacion: "2024-03-03",
    fechaFin: "2024-03-07",
    status: "Pendiente",
    categoria: "Taller",
  },
  {
    id: 16,
    nombreEvento: "Evento 4",
    tipoEvento: "Público",
    fechaCreacion: "2024-03-04",
    fechaFin: "2024-03-08",
    status: "Activo",
    categoria: "Conferencia",
  },
];
